import { createConfig, http } from "wagmi";
import {
  mainnet,
  optimism,
  cronos,
  telos,
  xdc,
  bsc,
  gnosis,
  unichain,
  polygon,
  monad,
  sonic,
  manta,
  fantom,
  zoraTestnet,
  metis,
  coreDao,
  moonbeam,
  sei,
  soneium,
  morph,
  mantle,
  klaytn,
  base,
  plasma,
  mode,
  arbitrum,
  hemi,
  avalanche,
  linea,
  berachain,
  blast,
  taiko,
  scroll,
  katana,
} from "wagmi/chains";
import { injected } from "wagmi/connectors";

export const wagmiConfig = createConfig({
  chains: [
    mainnet,
    optimism,
    cronos,
    telos,
    xdc,
    bsc,
    gnosis,
    unichain,
    polygon,
    monad,
    sonic,
    manta,
    fantom,
    zoraTestnet,
    metis,
    coreDao,
    moonbeam,
    sei,
    soneium,
    morph,
    mantle,
    klaytn,
    base,
    plasma,
    mode,
    arbitrum,
    hemi,
    avalanche,
    linea,
    berachain,
    blast,
    taiko,
    scroll,
    katana,
  ],
  connectors: [injected()],
  transports: {
    [mainnet.id]: http(),
    [optimism.id]: http(),
    [cronos.id]: http(),
    [telos.id]: http(),
    [xdc.id]: http(),
    [bsc.id]: http(),
    [gnosis.id]: http(),
    [unichain.id]: http(),
    [polygon.id]: http(),
    [monad.id]: http(),
    [sonic.id]: http(),
    [manta.id]: http(),
    [fantom.id]: http(),
    [zoraTestnet.id]: http(),
    [metis.id]: http(),
    [coreDao.id]: http(),
    [moonbeam.id]: http(),
    [sei.id]: http(),
    [soneium.id]: http(),
    [morph.id]: http(),
    [mantle.id]: http(),
    [klaytn.id]: http(),
    [base.id]: http(),
    [plasma.id]: http(),
    [mode.id]: http(),
    [arbitrum.id]: http(),
    [hemi.id]: http(),
    [avalanche.id]: http(),
    [linea.id]: http(),
    [berachain.id]: http(),
    [blast.id]: http(),
    [taiko.id]: http(),
    [scroll.id]: http(),
    [katana.id]: http(),
  },
});
